@startuml
skinparam dpi 300

'left to right direction

node "Mac" as mac {
  agent Quarkus as macquarkus
  action GraalVM as macgraalvm
}

cloud "Azure" as azure {
  node "Azure AppService" as azureappservice
  node "Postgres Flexible Server" as azurepostgres
  node "Azure OpenAI" as openAI
}

artifact "Native binary" as binary

mac .right.> binary
binary .right.> azureappservice

azureappservice ..> azurepostgres
azureappservice .> openAI
macquarkus -[hidden]-> macgraalvm
@enduml
