services:
    database:
        image: "postgres:17.4"
        container_name: "azure-monitoring-javaruntime-database"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
